# Generated by Django 4.1.7 on 2023-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
