# Generated by Django 4.1.7 on 2023-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(default=3),
        ),
    ]
