# Generated by Django 4.1.7 on 2023-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
